import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { IoIosTimer } from 'react-icons/io';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Punch Card',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className=" bg-gray-800">
          <div className="container mx-auto flex py-5">
            <a href="/">
              <span className="flex items-center space-x-2">
                <span>Dakoku App</span>
                <IoIosTimer size={23} />
              </span>
            </a>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
